cryptopelago/gitmoney

README.md

This PR updates the README with a basic overview of how Git Money works.

git-money: Update README

---

testing-webhooks.txt

Testing the Github web hook server

Git Money: Testing the Github webhook server

---

app/server.py
config.py
config/repos.json

Includes a webhook server that runs on port 21337 that can receive web hooks for "issue_comment" and "issue_comment" web hooks from github.
issue_comment: Creates and returns an object containing the issue url, the payout address held in the label, the payout amount also held in a label, and the body which is to contain the Bitcoin payout address.
pull_request: This web hook can be triggered upon several event, we ensure that merge status is True before following through with a payout. If merge status is true, we currently just print the body. In the future this body will need to be parsed for a payout address and the bounty amount.

Git Money: Github webhook server

---

app/wallet.py

Dev friendly payment wrapper for the 21BC wallet.

Git Money: 21BC Payment wallet wrapper

---

testing-webhooks.txt

#34  3CLetFLtMMCPHiEvcwEyQg5Jw6v4gXXaDE

git-money: Testing pull-request webhooks

---

README.md

13aWiexHS6mv8oqRy2wBb6uFsr2W3hzpKe

Revise README for prototype

---

test.txt

3CLetFLtMMCPHiEvcwEyQg5Jw6v4gXXaDE

Testing webhooks

---

test.txt

#51 34LeoU63TNGf78FP1stTV4YYx6Em3JpnPm

Revert "git-money: Testing pull-request webhooks"

---

app/cli.py
app/github.py
app/server.py
app/utils.py
app/wallet.py
config/repos.json
requirements.txt
test.txt

The automated send flow includes provisions for dynamic bounties and bounty addresses.

Automated send flow

---

config/repos.json

#86  35zAx4n5CYbVFpzLcgpdquMWCAWe5qM2Ce

Remove unneeded key field

---

app/github.py
app/multisig_wallet.py
app/server.py
config/repos.json

Fixes #86 35zAx4n5CYbVFpzLcgpdquMWCAWe5qM2Ce

Bitgo wallet

---

app/github.py
app/server.py

This fixes #102 Here is my address, please pay me here: 3CVMoKhg2ApDcDxtXikQHGPDDVvY6ubSuz

Finalize the BitgoWallet Send Flow

---

README.md

This PR updates the README to prepare for our upcoming pilot, to provide better clarity about git money and what it does. Also how it works.

Update README.md to prepare for Pilot

---

index.html
translations/english.html

alt attribute for images

---

index.html
translations/english.html

NOTE: If this pull request you are about to submit is to claim a bounty, please
make sure your pull request message text *correctly* resolves the corresponding
issue as described in the following article:
https://github.com/blog/1506-closing-issues-via-pull-requests
Also, please don't forget to include your bitcoin address in the text as well.
======ADD YOUR PR MESSAGE TEXT BELOW THIS LINE======
Closes #146
1AkQBiZHbLGYE4dVFnchPb2TbTj9cAHgRA

Revise alt text; send bounty to mousavian

---

translations/japanese.html

NOTE: If this pull request you are about to submit is to claim a bounty, please
make sure your pull request message text *correctly* resolves the corresponding
issue as described in the following article:
https://github.com/blog/1506-closing-issues-via-pull-requests
Also, please don't forget to include your bitcoin address in the text as well.
======ADD YOUR PR MESSAGE TEXT BELOW THIS LINE======
Translate home page to Japanese 
Fixes #134 
BTC: 3MyPjAW4obCGfm8E7R2cYLpxCLDivemxXp

including Japanese translated home page

---

index.html
js/custom.js
translations/english.html

NOTE: If this pull request you are about to submit is to claim a bounty, please
make sure your pull request message text *correctly* resolves the corresponding
issue as described in the following article:
https://github.com/blog/1506-closing-issues-via-pull-requests
Also, please don't forget to include your bitcoin address in the text as well.
======ADD YOUR PR MESSAGE TEXT BELOW THIS LINE======
- Add social sharing links - FB, Twitter & Google+  
- Fixes #147 
- Add Open Graph Metadata
- Fixes #148 
BTC: 1AkQBiZHbLGYE4dVFnchPb2TbTj9cAHgRA

Add social sharing links & open graph metadata

---

app/github.py

If you are submitting a pull request to collect a bounty, please submit it in
the following example format:
Resolves #123 (include the word 'Resolves' follwed by the issue number)
Bitcoin Address: 38aBVgK9tBvJM1HKmzVy3pAX6TsYdt51sH (your Bitcoin address)
Description: A brief high-level sentence or two describing your PR.
Please proceed with your pull request and remove this line and all preceding
text once you've completed your pull request message. Thanks for your
contribution!

Swapping from tradeblock to blockcypher

---

social/twitter.md

Resolves #158 
Bitcoin Address: 1DXNpiF3MQt4jYgdwX2iPQNTUhsf3vZ3tg
Description: Retweeted a tweet publicising git-money to my tribe. Also sharing across two slack chats.

Updated with retweet from @matthewjamesr

---

.gitignore
app/cli.py
app/github.py
app/server.py
config/config.json
setup.py

If you are submitting a pull request to collect a bounty, please submit it in
the following example format:
Resolves #123 (include the word 'Resolves' follwed by the issue number)
Bitcoin Address: 38aBVgK9tBvJM1HKmzVy3pAX6TsYdt51sH (your Bitcoin address)
Description: A brief high-level sentence or two describing your PR.
Please proceed with your pull request and remove this line and all preceding
text once you've completed your pull request message. Thanks for your
contribution!

Make it easier to get started with git money

---

translations/german.html

Resolves #136
Bitcoin Address: 1DXNpiF3MQt4jYgdwX2iPQNTUhsf3vZ3tg
Description: Translated index.html to German and placed file in "translations/german.html"

Created German Translation

---

translations/hindi.html

Resolves #133 
Bitcoin Address: 3DiDteqykxm1wCML2yhQw7cx4cNCKjUv6o
Description: translated all applicable english sentences to Hindi

Hindi Translation

---

social/twitter.md

Resolves #169 
Bitcoin Address: 3FjobKg82mY6xaMvMvwzND3YES37AcUFzf 
Description: Retweeted and tweeted from my account.

tweeted and re-tweeted

---

translations/greek.html

Submission for a greek translation of the webpage.
Resolves #142
1DpXSfwBwZwg66tKV8oMj7uPvmhBTeJdfy

greek.html

---

translations/russian.html

Resolves #144 
Bitcoin Address: 1GG3sg3Etp5VjfV5j2S2fZ9DpNsXqAKtWA
Description: Translated text in index.html to Russian and add to /translations/ folder as russian.html

adding russian translation with changes

---

translations/spanish.html

Resolves #138
Bitcoin Address: 143V7CCnxZGhxXAXfFXyyXeUKigCQXctzR
Description: Translated index.html to spanish

Added spanish translation of index.html

---

social/medium.md

Resolves #195 
Bitcoin Address: 15Dq95bjnkKwVBmSiPkjNVK45Gx29Aoggp
Description: Added new article to Medium for Git Money.

Updated medium.md

---

README.md
index.html

This PR removes a couple of unnecessary links and revises some wording.

Binns content revisions

---

social/medium.md

Resolves #207 
Bitcoin Address: 1sF7GoCq1zrMg8xeKHjuafgAq5brQcy3X
Description: Added an interesting article to Medium for Git Money.

Add New Medium Story #207

---

translations/dutch.html

Resolves #135 
Bitcoin Address: 1M78rSGWrYjaYeMtj7mpQqDEKPLAsg3o36

Added Dutch translation for homepage in translations/dutch.html

---

newlogos.md

Resolves #184
Bitcoin Address: 1sF7GoCq1zrMg8xeKHjuafgAq5brQcy3X
Description: Finally made some cool but unique minimalist logos for GitMoney that are high-resolution and in both PNG/PSD!
Here's a link to the entire folder: https://app.box.com/s/amkp9jtwuojt7vp9lymc2ytyg8tdteav
The markdown file that I want to add is merely links to the singular files for the different logos.

(Resolve #184) Cool minimalist logos for Gitmoney

---

translations/spanish.html

Resolves #214
Bitcoin Address: 1KWzcnhDMpBm4AcHjuXfJuKEMbqmuz3NAW
Description: I reviewed the existing Spanish translation. 
The existing translation was spot on, but the formatting and main message component of the website (Brief Left section) were missing.
So I added that back and translated it exactly. 
I also fixed the navigation of the toggle bar as well and some punctuation here and there

Reviewed Spanish.html

---

translations/russian.html

Resolves #213 
Bitcoin Address: 1NVNvEC7qj7ANabdms2dK9GGsbSyJ52WMx
Description: Committed actual translation, in place of machine-generated one, which was, needles to say, a bit off.

Commiting some actual russian translation

---

translations/portuguese.html

Resolves #137
Bitcoin Address: 1Mn639ga5FwgHrwTKdMUtcBLemoYPS1HWt
Description: Translated index.html to Portuguese and placed file in "translations/portuguese.html"

Created Portuguese Translation

---

translations/italian.html

Resolves #141
Bitcoin Address: 1HamukiBbYq5Fe5mL2ZHCELemr4f7WHu6t
Description: Add italian translation.

Add italian translation.

---

translations/greek.html

Resolves: #210 
Description: Fixed greek translation, improved language style, translate some meta keywords, fixed some typos
Bitcoin Address: 1EZkxj7fG195KQrbBCk2mWqyLV8sBBJkxK

Resolve: #210 fixed greek translation

---

translations/portuguese-br.html

Resolves #137
Bitcoin Address: 1JNkknaPhrYewodyQS7GY31Pa8rQQSWsd5
Description: Unfortunately i couldn't preview the page, but i took a lot of care with the markup and the portuguese itself. My native portuguese is from Brazil so you might want to open another issue for someone to duplicate and review from a Portugal's perspective.
__*NOTE*__:
I have simplified the translation since "However you choose to git money" and "It's completely up to you" sounded very redundant in portuguese

adding pt-br translation

---

social/youtube.md

Resolves #196
Bitcoin Address:  	1DpXSfwBwZwg66tKV8oMj7uPvmhBTeJdfy

youtube.md

---

index.html
public/css/datatables.css
public/js/custom.js

Resolves N/A
Bitcoin Address: 1Mn639ga5FwgHrwTKdMUtcBLemoYPS1HWt
Description: Added bounties / issues table (see 21 hackers session)

Added bounties / issues table

---

translations/german.html

Resolves #209
Bitcoin Address: 1HM8xEpwB6gWWsnEHjv8xki5WWbdK3nFAc 
Description: Added Corrections to the german translation.

Added corrections to the german translation. 

---

translations/chinese.html

Resolves #139
Bitcoin Address: 1HK2LYk1jFBWUFgx936zEekqB3Z2poDcgh
Description: Chinese translation added

Chinese translation added #139

---

translations/turkish.html

Resolves:
Bitcoin Address: 1MVjVwkEye65FxvzKEQcKFsZQThe1WowyR
Description: A brief high-level sentence or two describing your PR.
I do not see any issue with Turkish home page translate but , I'm translated the home page.

Translate home page to Turkish

---

translations/swedish.html

Resolves #143
Bitcoin Address: 18TdWdApt7X8tquLdZ275e1MguhTDWtvKd
Description: Swedish translation of the html.

added Swedish translation (Resolves #143)

---

app/github.py
app/utils/marketplace_server.py
app/wallet.py

Updated the two1 library packages since they were moved with the latest updates.
**Code Examples:**
_Former Version_ 
`from two1.lib.wallet import Wallet`
_Updated Version_
`from two1.wallet import Wallet`

updated two1 library packages

---

index.html

This adds an email sign up to the Git Money website.

index: Add email sign up

---

social/facebook.md

BTC address: 1F63CxV5vCN1b4MELgW3vuoRDMrdnJbU3Y

link added
